# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :create_app do
	produce
	upload_app_privacy_details_to_app_store(
  	username: "",
  	team_name: "",
  	app_identifier: ""
)
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Take screenshots"
  lane :screenshots do
    snapshot
    frame_screenshots(white: true)
  end

  desc "Create ipa"
  lane :build do
    # 1
    enable_automatic_code_signing
    # 2
    increment_build_number
    # 3
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

end
